version: '2.1'

services:
  mongodb:
    extra_hosts: &hosts
      - 'api.assets.dev.ds:${PROXY_HOST}'
      - 'api.authentication.dev.ds:${PROXY_HOST}'
      - 'api.camunda.dev.ds:${PROXY_HOST}'
      - 'api.cases.dev.ds:${PROXY_HOST}'
      - 'api.cms.dev.ds:${PROXY_HOST}'
      - 'api.discovery.dev.ds:${PROXY_HOST}'
      - 'api.formio.dev.ds:${PROXY_HOST}'
      - 'api.forms.dev.ds:${PROXY_HOST}'
      - 'api.identities.dev.ds:${PROXY_HOST}'
      - 'api.interactions.dev.ds:${PROXY_HOST}'
      - 'api.logs.dev.ds:${PROXY_HOST}'
      - 'api.records.dev.ds:${PROXY_HOST}'
      - 'api.services.dev.ds:${PROXY_HOST}'
      - 'api.tasks.dev.ds:${PROXY_HOST}'
      - 'api.tenants.dev.ds:${PROXY_HOST}'
      - 'api.topics.dev.ds:${PROXY_HOST}'

  formio:
    extra_hosts: *hosts

  registrator:
    extra_hosts: *hosts

  adminer:
    image: adminer:4-standalone
    environment:
      VIRTUAL_HOST: '${ADMINER_VIRTUAL_HOST}'
      SERVICE_IGNORE: 'true'
    extra_hosts: *hosts
    links:
      - mongodb:formio_mongodb
