version: '2.1'

volumes:
    formio_mongodb_data:
        driver: local

    formio_formio_data:
        driver: local

services:
    formio_mongodb:
        image: mongo:3.4.3
        volumes:
            - formio_mongodb_data:/data/db
        healthcheck:
            test: ['CMD-SHELL', 'echo "db.stats().ok" | mongo localhost/formioapp --quiet']
            interval: 5s
            timeout: 1s
            retries: 10

    formio_formio:
        build: .
        depends_on:
            formio_mongodb:
                condition: service_healthy
        environment:
            - VIRTUAL_HOST
        volumes:
            - formio_formio_data:/data
        extra_hosts:
            - 'api.assets.ds:${PROXY_HOST}'
            - 'api.authentication.ds:${PROXY_HOST}'
            - 'api.camunda.ds:${PROXY_HOST}'
            - 'api.cases.ds:${PROXY_HOST}'
            - 'api.cms.ds:${PROXY_HOST}'
            - 'api.discovery.ds:${PROXY_HOST}'
            - 'api.formio.ds:${PROXY_HOST}'
            - 'api.identities.ds:${PROXY_HOST}'
            - 'api.interactions.ds:${PROXY_HOST}'
            - 'api.logs.ds:${PROXY_HOST}'
            - 'api.records.ds:${PROXY_HOST}'
            - 'api.services.ds:${PROXY_HOST}'
            - 'api.tasks.ds:${PROXY_HOST}'
            - 'api.topics.ds:${PROXY_HOST}'

networks:
    default:
        external:
          name: '${NETWORK}'
