version: '2.1'

services:
  formio:
    build:
      context: ./formio

  database_ui:
    image: adminer:4-standalone
    links:
      - mongodb:formio_mongodb
    networks:
      default:
        aliases:
          - formio_database_ui
