version: '2.1'

services:
  mongodb:
    image: mongo:3.4.3
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD-SHELL', 'echo "db.stats().ok" | mongo localhost/formioapp --quiet']
      interval: 5s
      timeout: 1s
      retries: 10
    networks:
      default:
        aliases:
          - formio_mongodb

  formio:
    image: digitalstate/formio:0.17.0
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      USERNAME: ${API_ADMIN_USER}
      PASSWORD: ${API_ADMIN_PASSWORD}
      FORMIO_DEFAULT_JSON: ${FORMIO_DEFAULT_JSON}
    volumes:
      - formio_data:/data
    links:
      - mongodb:formio_mongodb
    networks:
      default:
        aliases:
          - formio_formio

volumes:
  mongodb_data:
    driver: local

  formio_data:
    driver: local
