version: '2'

services:
  formio:
    build: .
    environment:
      MONGODB_USERNAME: 'mongo'
      MONGODB_PASSWORD: 'mongo'
      MONGODB_DBNAME: 'admin'
      MONGODB_ROLE: 'dbAdminAnyDatabase'
      FORMIO_MONGO_DSN: 'ChangeThisValue'
      FORMIO_MONGO_SECRET: 'ChangeThisValue'
      FORMIO_JWT_SECRET: 'ChangeThisValue'
    ports:
      - '27017:27017'
      - '28017:28017'
      - '8888:8080'
      - '3001:3001'
    volumes:
      - './formio:/opt/formio'

volumes:
  formio: {}
#    driver: local
