version: '2.1'

services:
  mongodb:
    image: mongo:3.4.3
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ['CMD-SHELL', 'echo "db.stats().ok" | mongo localhost/formioapp --quiet']
      interval: 5s
      timeout: 1s
      retries: 10

  formio:
    build: .
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST
      - USERNAME
      - PASSWORD
      - FORMIO_DEFAULT_JSON
    volumes:
#      - '${DIRECTORY}/formio:/srv/formio'
      - formio_data:/data
    links:
      - mongodb:formio_mongodb

volumes:
  mongodb_data:
    driver: local

  formio_data:
    driver: local

networks:
  default:
    external:
      name: '${NETWORK}'
